// src/components/faqs/FaqText.tsx
import Picture1 from "../../assets/faqImages/Picture1.png";
import Picture2 from "../../assets/faqImages/Picture2.png";
import Picture3 from "../../assets/faqImages/Picture3.png";
import Picture4 from "../../assets/faqImages/Picture4.png";

export const generalFaqs = [
  {
  question:
      "What types of renewable energy production does the DRE Service forecast?",
    answer:
      "The DRE Service provides forecasts for solar photovoltaic (PV) and wind energy production. It leverages meteorological and historical data to deliver accurate generation predictions for both energy types across various geographic regions.",
  },
  {
    question: "I am not an expert user. How can I interpret the output graphs?",
    answer: `DRE is a scientific service tailored to the needs of experts and professionals. It includes energy assessment and forecasting based on input provided by end-users. At each step, specific guidance notes are provided to assist end-users. </br> </br>
    <p>Users who are not familiar with energy forecasting methodologies are encouraged to review the MOOC or User Guide for both solar and wind services.</p>
    `,
  },
  {
    question: "What is the forecast horizon provided by the DRE Service?",
    answer:
      "The forecast horizon extends up to 48 hours, depending on the subscription plan. Users can typically access forecasts ranging from hourly to monthly intervals, supporting both short-term operations and long-term planning.",
  },
  {
    question: "What user-provided input data is required to generate customized forecasts?",
    answer:
    `To generate a customised forecast, users typically need to provide the following input information: </br></br>
    <ul>
    <li>●	Geographic location (latitude/longitude)</li>
    <li>●	System configuration (capacity, tilt, azimuth, etc.)</li>
    <li>●	User's Park Data</li>
    </ul>
    `,
  },
  {
    question:
      "Once a processing job is complete, how can I visualize the outputs?",
    answer: `The outputs will appear directly on your screen in the Archive section. Click "Visualise" to view the results of the requested forecasting. </br></br>
    Forecast results are presented through: </br></br>
    <ul>
    <li>●	Interactive dashboards</li>
    <li>●	Time series graphs</li>
    </ul>
    </br></br>
    These visuals enable quick insights into expected performance and variability.
    `,
  },
  {
    question: "Can users download the forecasted data generated by DRE?",
    answer:
      "Yes. Users can export data in CSV, PNG or SVG formats, depending on their needs. Data export is available for both raw forecast outputs.",
  },
  {
    question: "Can users access the previous results they generated on DRE?",
    answer:
      "Yes, the platform maintains a historical archive of assessments and forecast results, allowing users to retrieve past outputs.",
  },
  {
    question:
      "Is the free tier time-limited, and can users upgrade to another plan directly via DRE?",
    answer:
      "The free tier is available with feature limitations, not time-limited. Users can upgrade to other plans directly through the platform to unlock extended features, support, and data granularity.",
  },
]

export const solarFaqs = [
  {
    question:
      "What is solar irradiation, and how is it measured in your forecasts?",
    answer:
      "Solar irradiation refers to the power per unit area received from the Sun in the form of electromagnetic radiation. It’s measured in kilowatt-hours per square meter (kWh/m²) and represents the total energy received on a surface over time, which is crucial for estimating solar power output.",
  },
  {
    question:
      "What is the difference between solar irradiation and solar power output?",
    answer:
      "Solar irradiation is an environmental input — the sunlight energy available. Solar power output (in kW) is the system's response, determined by how efficiently your solar panels convert that energy into electricity, influenced by panel specs, angle, weather, and system losses.",
  },
  {
    question:
      "What are the main atmospheric factors affecting solar irradiation forecasts?",
    answer:
      " Key atmospheric variables include cloud cover, aerosol optical depth, water vapor content, and solar zenith angle. These are integrated in radiative transfer models used in weather-based irradiation forecasting.",
  },
  {
    question:
      "What kind of data is used for the training of the machine learning solar forecasting model, to predict solar radiation?",
    answer:
      "We use the user uploaded dataset and combine it with data from the CAMS McClear and HelioClim-3 services, which rely on satellite-based radiative transfer models and real-time atmospheric data to simulate surface solar irradiance under clear-sky and all-sky conditions.",
  },
  {
    question:
      "How accurate is the CAMS/ radiation data used in your system?",
    answer:
      "CAMS data offers high temporal (hourly) and spatial (up to 2–5 km resolution) accuracy. Its validation against ground measurements shows mean bias errors below ±10% for hourly Global Horizontal Irradiance (GHI), making it suitable for forecasting applications.",
  },
  {
    question:
      "What temporal resolution does your forecast offer?",
    answer:
      "Forecasts are provided in hourly intervals, covering a full 48-hour horizon. This resolution balances computational efficiency with operational relevance for planning and grid management.",
  },
  {
    question:
      "How do you account for shading or soiling in the forecast?",
    answer:
      "Our forecast assumes declared system conditions. System derating factors or historical performance losses are also incorporated into the uploaded historical data used in the training of the model, and thus taken into account.",
  },
  {
    question:
      "How are seasonal changes accounted for in forecasts?",
    answer:
      "Seasonality is inherently modeled through the variation in solar zenith angles and day length, as well as seasonal atmospheric composition (e.g., aerosols, humidity), which are captured in the dynamic CAMS inputs.",
  },
  {
    question:
      "What happens if I don’t have historical data to upload?",
    answer:
      "No problem — we can still generate reliable forecasts using your park’s characteristics such as location, size, orientation, and tilt.",
  },
  {
    question:
      "How often is the forecast updated?",
    answer:
      "With the Annual Subscription plan, forecasts are automatically updated daily. The One-Time Forecast provides a single 2-day outlook.",
  },
  {
    question:
      "Can this service support grid integration studies or energy yield assessments?",
    answer:
      "Yes. Our forecast data can be used as input for grid balancing, battery dispatch strategies, and long-term yield analysis when aggregated and combined with system performance modeling.",
  },
  {
    question:
      "How does the DRE Service calculate irradiation forecasts and energy production forecasts?",
    answer:
      "The DRE Service uses DT forecasting data, which is locally adapted using available user input. The adjusted forecast fields are then used to estimate the potential wind energy yield based on a wind power curve. The power curve model can be predefined, provided by the user or calculated through the data the user uploads.",
  }, 
]

export const windFaqs = [
  {
    question: "What is a Wind Turbine Power Curve?",
    answer: `A <strong>Power Curve</strong> is a graph that shows how much electricity a wind turbine can generate at different wind speeds. </br></br>
    <ul>
    <li>●	The horizontal axis is the wind speed</li>
    <li>●	The vertical axis is the power output</li>
    </ul>
    </br></br>
    See an example bellow: 
    </br></br>
    <img src="${Picture1}" alt="Power Curve Example" />
    `,
  },
  {
    question: "How is Wind Energy Output Calculated from Power Curves?",
    answer:
      "Wind energy output is calculated by matching horizontal wind speed data (e.g., hourly values) to the turbine’s power curve to find the corresponding power.",
  },
  {
    question: "What is Total Energy Potential (kWh)?",
    answer:
      "This is the total amount of energy a wind turbine is expected to generate over the analysis period (e.g., a year or a specific number of hours), based on wind data and the turbine’s power curve.",
  },
  {
    question: "What is Average Power Output (kW)?",
    answer:
      "This represents the average rate of energy production over the given period. It is calculated by dividing the total energy generated by the total time (in hours).",
  },
  {
    question: "What is Capacity Factor?",
    answer:
      "The capacity factor indicates how efficiently a turbine operates over time. It iss the ratio between the actual energy produced and the energy it could have produced if it ran at full capacity the entire time.",
  },
  {
    question: "What is the Mean Wind Speed (m/s)?",
    answer:
      "This is the average wind speed observed during the selected period. It helps evaluate the windiness of a site and is a key input for estimating energy production.",
  },
  {
    question: "What is Wind Power Density (W/m²)?",
    answer:
      "Wind power density measures the available power in the wind per square meter, based on wind speed and air density. It reflects the energy content of the wind and is used to assess site suitability for wind power.",
  },
  {
    question: "What is a Wind Rose and What is it Used For?",
    answer: `A <strong>Wind Rose</strong> shows how wind typically behaves at a specific location over a period of time. It provides a visual summary of how often the wind blows <strong>from different directions</strong> and, in some cases, <strong>how strong</strong> it is when it does.`,
  },
  {
    question: "How to read the Wind Rose provided in DRE?",
    answer: `<img src="${Picture2}" alt="Wind Rose Example" /> 
    <ul>
    <li>●	The <strong>length of the bars</strong> indicates how common winds are from that direction — the longer the bar, the more frequent the wind from that direction (in percentage %).</li>
    <li>●	The <strong>colors</strong> show that the <strong>wind speed</strong> is grouped into ranges. Lighter colors indicate lower wind speeds, while darker shades represent stronger winds.</li>
    <li>●	The chart is arranged like a compass, so each direction (N, NE, E, etc.) tells you where the wind is blowing <strong>from</strong>.</li>
    </ul>`,
  },
  {
    question: "What is a Wind Speed Histogram?",
    answer:
      "A <strong>wind speed histogram</strong> is a simple bar chart that shows how often different wind speeds (at predefined bins) occur at a specific location over a time period. It helps us understand the <strong>distribution of wind speeds</strong>, without considering which direction the wind is blowing from.",
  },
  {
    question:
      "What is a Weibull Distribution, and why is it used for Wind Speed?",
    answer: `The <strong>Weibull distribution</strong> is a mathematical function commonly used to describe <strong>how wind speeds are spread out</strong> at a specific location. It’s a smooth curve that gives a good approximation of how often certain wind speeds occur. It helps summarize complex wind data with just two key parameters:
    </br></br>
    <ul>
    <li>●  <strong>Shape (k)</strong>: Shows how peaked or spread the wind speeds are.</li>
    <li>●	<strong>Scale (c)</strong>: Reflects the average windiness of the site.</li>
    </ul>
    </br></br>
        <ul>
    <li>●   Captures the <strong>most likely wind speeds</strong></li>
    <li>●	Estimates the <strong>probability of extreme winds</strong>, and</li>
    <li>●	Supports <strong>wind energy assessments</strong>, especially for turbine design and energy yield forecasting.</li>
    </ul>    
    `,
  },
  {
    question: "How to read the following figure provided by DRE?",
    answer: `<img src="${Picture3}" alt="Weibull Distribution Example" />
    <ul>
    <li>●	<strong>The histogram (in cyan)</strong> shows how frequently different wind speeds occur at the selected location. Taller bars represent more common wind speeds. The <strong>left y-axis</strong> displays this frequency (as probability density).</li>
    <li>●	The <strong>red curve</strong> is a <strong>Weibull distribution</strong> fitted to the same wind speed data. It provides a smooth approximation of the wind pattern, helping to model the likelihood of each wind speed - including values that may not appear often in the raw data.</li>
    <li>●	The <strong>horizontal blue lines</strong> represent the <strong>mean annual energy production</strong> associated with each wind speed range, based on a predefined wind power curve. They show how energy output depends not just on wind speed intensity, but also on how frequently each speed occurs. The energy peak emerges where both factors align. The right <strong>y-axis</strong> displays the mean annual estimated energy.</li>
    </ul>`,
  },
  {
    question: "What do the directional statistic outputs refer to?",
    answer: `
    <ul>
    <li>●	<strong>Direction</strong>: The wind direction the data refers to — where the wind is coming from (e.g., N, NE, E).</li>
    <li>●	<strong>Frequency (%)</strong>: The percentage of time the wind comes from that direction</li>
    <li>●	<strong>Weibull Shape (k)</strong>: A parameter that defines the spread of wind speeds; higher values mean wind speeds are more consistent.</li>
    <li>●	<strong>Weibull Scale (c)</strong>: A parameter that reflects the typical wind speed; closely related to the mean wind speed.</li>
    <li>●	<strong>Mean Wind Speed (m/s)</strong>: The average wind speed from that direction.</li>
    <li>●	<strong>95th Percentile (m/s)</strong>: The wind speed value that is exceeded 5% of the time — shows the strength of occasional stronger winds.</li>
    <li>●	<strong>97th Percentile (m/s)</strong>: Wind speed exceeded 3% of the time — useful for assessing rare but relevant high-wind events.</li>
    <li>●	<strong>99th Percentile (m/s)</strong>: Wind speed exceeded just 1% of the time — often used in structural design or turbine safety analysis.</li>
    </ul>`,
  },
  {
    question: "How to ready the following figure provided by DRE?",
    answer: `<img src="${Picture4}" alt="Weibull Distribution Example" />
    <ul>
    <li>●	This figure illustrates a timeseries showing the evolution and the <strong>relationship between wind speed and power generation</strong>.</li>
    <li>●	<strong>X-axis</strong>: Time progression from midnight on the 24th to midnight on the 26th of November.</li>
    <li>●	<strong>Left Y-axis</strong> (kW): Forecasted power output from the wind turbine.</li>
    <li>●	<strong>Right Y-axis</strong> (m/s): Wind speed.</li>
    </ul>
    `,
  },
]