FROM python:3.11-slim
WORKDIR /app
COPY . /app
COPY celery_app.py tasks.py ./

# Configure Matplotlib cache
ENV MPLCONFIGDIR=/tmp
RUN mkdir -p /tmp && chmod 1777 /tmp

# Install cams_tools package
COPY cams_tools/ ./cams_tools/

RUN pip install ./cams_tools

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY app.py main.py celery_app.py tasks.py /app/

# Set environment variables (if needed)
ENV DEDL_USERNAME kpapachr@noa.gr
ENV DEDL_PASSWORD buc4gup*dat3HVB9unu

# Expose port and start Uvicorn
EXPOSE 8000
ENTRYPOINT ["uvicorn", "app:asgi_app", "--host", "0.0.0.0", "--port", "8000"]