version: '3'

services:
  solar-forecast-api:
    image: dre/solar-forecast-inference/app-backend:1.0.1
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./models:/app/models
      - ./data_pool:/app/data_pool
    environment:
      - NOTIFICATION_URL=https://hyrefapp.dev.desp.space/api/Jobs/jobresult
      - NOTIFICATION_TOKEN=916ab7c8-acb39e299883-f1ca-419b-816b-7cfb307e6daf883b-aa91b02090b8
      - CAMS_USER=kpapachr@noa.gr
      - CAMS_PASSWORD=buc4gup*dat3HVB9unu
      - AOD_LOOKUP_TABLE_PATH=/app/aod_variables/eglo_surf_lut_cs_high_res_NAcorrected_alb02.Rdata
      - STATION_CLIMATE_PATH=/app/aod_variables/station_clima.csv
    restart: unless-stopped