version: '3'

services:
  solar-forecast-api:
    image: dre/solar-forecast-inference/app-backend:1.0.1
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./models:/app/models
      - ./data_pool:/app/data_pool
    environment:
      - NOTIFICATION_URL=
      - NOTIFICATION_TOKEN=
      - CAMS_USER=
      - CAMS_PASSWORD=
      - AOD_LOOKUP_TABLE_PATH=/app/aod_variables/eglo_surf_lut_cs_high_res_NAcorrected_alb02.Rdata
      - STATION_CLIMATE_PATH=/app/aod_variables/station_clima.csv
    restart: unless-stopped