name: destine
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - xarray
  - eccodes
  - fastapi
  - uvicorn
  - requests
  - tqdm
  - pydantic
  - pip
  - pip:
      - cfgrib==0.9.14.0
      - ./destinelab-1.1.tar.gz
      - cdsapi>=0.7.4
